CREATE TABLE ROOTBOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(1000),
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE TABLE REPLYBOARD(
	SEQ NUMBER NOT NULL,
	REF NUMBER PRIMARY KEY,
	P_ID VARCHAR2(30) NOT NULL,
	P_CONTENT VARCHAR2(1000) NOT NULL,
	P_DELFLAG CHAR(1) NOT NULL,
	P_REGDATE DATE NOT NULL
);


--답글 게시판 이후 파일 업로드 게시판 만들기
--CREATE TABLE FILEBOARD(
--	
--);

--조회
SELECT *
	FROM ROOTBOARD r ;

SELECT *
	FROM REPLYBOARD r ;

INSERT INTO ROOTBOARD
(SEQ, ID, TITLE, CONTENT, DELFLAG, REGDATE)
VALUES(1, '부로꼬리', '맛 좋은 브로콜리', '삶아서 초장에 찍어드세요', 'N', SYSDATE);

-- 원글 등록
INSERT INTO ROOTBOARD
(SEQ, ID, TITLE, CONTENT, DELFLAG, REGDATE)
VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM ROOTBOARD), 'CHESTNUT', '기르던 쪼꼬푸들 찾아요', '제 쪼푸가 가출햇어요ㅠㅠ 찾아주세요ㅠㅠ', 'N', SYSDATE);


INSERT INTO REPLYBOARD
(SEQ, "REF", P_ID, P_CONTENT, P_DELFLAG, P_REGDATE)
VALUES(1, 1, 'DDP', '살림 꿀팁 감사 뿅', 'N', SYSDATE);

INSERT INTO REPLYBOARD
(SEQ, "REF", P_ID, P_CONTENT, P_DELFLAG, P_REGDATE)
VALUES(1, 2, 'ACE', '브로콜리 맛 없어요..', 'N', SYSDATE);


-- ROOT글 목록 조회

SELECT SEQ, ID, TITLE, DELFLAG, REGDATE
FROM ROOTBOARD;

-- 글 상세조회
SELECT r.SEQ , ID, TITLE, CONTENT, REGDATE, 
		"REF" , P_ID ,P_CONTENT , P_REGDATE 
	FROM ROOTBOARD r LEFT JOIN REPLYBOARD r2 
	ON r.SEQ = r2.SEQ ;


-- 글 입력
INSERT INTO REPLYBOARD
(SEQ, "REF", P_ID, P_CONTENT, P_DELFLAG, P_REGDATE)
VALUES(1, (SELECT NVL(MAX("REF"),0)+1 FROM REPLYBOARD), 'DANNA', '골고루 먹어야 키가 큰다', 'N', SYSDATE);

-- ROOT글 수정
UPDATE ROOTBOARD
SET TITLE='맛 없는 브로콜리', CONTENT='브로콜리 드시지 마세요 나만 먹을 거임'
WHERE SEQ=1;

--ROOT글 삭제
UPDATE ROOTBOARD SET DELFLAG = 'Y' WHERE SEQ=2;

--REPLY 수정
UPDATE REPLYBOARD SET P_CONTENT='이제 맛있어졋어요..' WHERE REF=2;

--REPLY 삭제
UPDATE REPLYBOARD SET P_DELFLAG = 'Y' WHERE "REF"=2;





